version: '2'
services:
  proxy:
    image: nginx
    ports:
        - "80"
    links:
        - apollo
        - galaxy
    volumes:
        - "./nginx/conf:/etc/nginx/conf.d"
  galaxy:
    build: galaxy
    environment:
        NONUSE: nodejs,proftp,reports
        GALAXY_LOGGING: full
        GALAXY_WEBAPOLLO_URL: "http://apollo:8080/apollo"
        GALAXY_WEBAPOLLO_EXT_URL: "/apollo"
        GALAXY_WEBAPOLLO_PASSWORD: "admin"
    volumes:
        - "./data:/apollo-data"
  apollo:
    image: gmod/apollo:stable
    links:
      - "apollo_db:db"
    environment:
      WEBAPOLLO_DB_USERNAME: postgres
      WEBAPOLLO_DB_PASSWORD: password
      WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_DB_URI: "jdbc:postgresql://db/postgres"
    volumes_from:
        - "galaxy:ro"
  apollo_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  apollo_admin:
    build: apollo
    links:
        - apollo
    environment:
      ADMIN_USERNAME: galaxy@gmod.org
      ADMIN_FIRST_NAME: Galaxy
      ADMIN_LAST_NAME: Admin
      ADMIN_PASSWORD: admin
